[originals]
title = "alookso ─ 오리지널"
url = "https://alook.so/originals"
entrySelector = "div[class='hidden px-4 lg:px-12 posts-post md:block group-post-body-visible']"
titleSelector = "div[class='text-lg font-semibold text-gray-800 break-all line-clamp-1 group-hover:underline group-hover:cursor-pointer decoration-gray-800 underline-offset-1'] a"
linkSelector = "div[class='text-lg font-semibold text-gray-800 break-all line-clamp-1 group-hover:underline group-hover:cursor-pointer decoration-gray-800 underline-offset-1'] a"
contentSelector = "h6.font-normal.text-gray-500 div[class*='trix-content']"
imageSelector = "div[class='w-48 h-32'] img"
waitUntil = "networkidle"
onFail = "stale"

[alookso-editor]
title = "alookso ─ alookso 에디터팀"
url = "https://alook.so/users/x4WtnB"
entrySelector = "div[class='divide-y-8 divide-gray-100 group-post-list-divide-base:divide-y'] div div[id^='post']"
titleSelector = "p[data-qa='post-title']"
linkSelector = "h6 a.trix-content-post-partial"
contentSelector = "h6 > a > div.break-all.trix-content.line-clamp-3"
imageSelector = "div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-platform]
title = "alookso ─ alookso 플랫폼팀"
url = "https://alook.so/users/bvZt3k"
entrySelector = "div[class='divide-y-8 divide-gray-100 group-post-list-divide-base:divide-y'] div div[id^='post']"
titleSelector = "p[data-qa='post-title']"
linkSelector = "h6 a.trix-content-post-partial"
contentSelector = "h6 > a > div.break-all.trix-content.line-clamp-3"
imageSelector = "div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-data]
title = "alookso ─ alookso 데이터팀"
url = "https://alook.so/users/bA6tp1"
entrySelector = "div[class='divide-y-8 divide-gray-100 group-post-list-divide-base:divide-y'] div div[id^='post']"
titleSelector = "p[data-qa='post-title']"
linkSelector = "h6 a.trix-content-post-partial"
contentSelector = "h6 > a > div.break-all.trix-content.line-clamp-3"
imageSelector = "div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-newsmot]
title = "alookso ─ alookso 뉴스못"
url = "https://alook.so/users/k6tVXZ"
entrySelector = "div[class='divide-y-8 divide-gray-100 group-post-list-divide-base:divide-y'] div div[id^='post']"
titleSelector = "p[data-qa='post-title']"
linkSelector = "h6 a.trix-content-post-partial"
contentSelector = "h6 > a > div.break-all.trix-content.line-clamp-3"
imageSelector = "div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-brf]
title = "alookso ─ alookso 브리프"
url = "https://alook.so/users/0Btk1l"
entrySelector = "div[class='divide-y-8 divide-gray-100 group-post-list-divide-base:divide-y'] div div[id^='post']"
titleSelector = "p[data-qa='post-title']"
linkSelector = "h6 a.trix-content-post-partial"
contentSelector = "h6 > a > div.break-all.trix-content.line-clamp-3"
imageSelector = "div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"
