[originals]
title = "alookso ─ 오리지널"
url = "https://alook.so/originals"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "div.relative.z-0.flex.-space-x-4 a:nth-child(1) img"
waitUntil = "networkidle"
onFail = "stale"

[alookso-editor]
title = "alookso ─ alookso 에디터팀"
url = "https://alook.so/users/x4WtnB"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-platform]
title = "alookso ─ alookso 플랫폼팀"
url = "https://alook.so/users/bvZt3k"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-data]
title = "alookso ─ alookso 데이터팀"
url = "https://alook.so/users/bA6tp1"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-newsmot]
title = "alookso ─ alookso 뉴스못"
url = "https://alook.so/users/k6tVXZ"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[alookso-brf]
title = "alookso ─ alookso 브리프"
url = "https://alook.so/users/0Btk1l"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"